name: Deploy to Server

on:
  push:
    branches:
      - main  # Adjust if you want a different branch to trigger deployment

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install SSH key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to Server
      run: |
        ssh -o StrictHostKeyChecking=no root@14.139.56.17 << 'EOF'
          cd /var/www/html/cseWebsite/CseBackend/userService &&
          git pull origin main &&
          cd /var/www/html/cseWebsite &&
          docker compose up -d --build
        EOF
